### ISSUE TITLE
`make check -j` fungerer ikkje i bash for nouns/propernouns i `src/fst/morphology/test/`

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sma#100]
@flammie eg får svært ulike testresultat for `generate-propernoun-lemmas.sh` med `make check -j` og `make devtest`/`make check` (dvs utan `-j`):

- `make check -j`: alle lemma feilar for nouns og propernouns
- `make devtest`/`make check` (utan `-j`): alt ok

**Comment by snomos** [comment]
Dette gjeld òg i CI, og er grunnen til at SMA feilar der no. Det er difor viktig å finna ut kva som er problemet.

**Comment by snomos** [comment]
Det fungerte på mi eiga maskin, men gjer det ikkje i [CI](https://github.com/giellalt/lang-sma/runs/25547889627). Eg forstår ikkje kva som skjer - @flammie, gjer du?

**Comment by snomos** [comment]
Eg testa meir, og fann ut at skilnaden no er mellom bash og zsh. Med den endringa eg gjorde over, så fungerer alt som det skal i zsh, men bash produserer same feil som tidlegare. Eg reknar med at CI-maskina køyrer bash, og at det er grunnen til at CI feilar.

@flammie har du ein idé om kva som kan vera problemet? @albbas ?

**Comment by snomos** [comment]
Har @TinoDidriksen eller @unhammer forslag til kva som kan vera problemet med parallelle testar? Observasjonar så langt:

- gjeld berre `propernouns` og `nouns` - problemet forsvann frå `zsh` når eg endra `propernouns` til `propers` internt i testskriptet
- gjeld berre når ein køyrer `make check` med `-j`
- gjeld ikkje lenger `zsh`, men gjeld `bash`, som er i bruk på dei fleste maskinene, inkl. CI

**Comment by flammie** [comment]
kanskje den fikser allt: https://github.com/giellalt/lang-sma/commit/f2dc75836e07f861280940068ec25b27546e40b8, den ene testen bara i sma prover og rydde bort alle genererte testfiler

**Comment by snomos** [comment]
Jepp, det var det, no funkar make check i bash òg :)
