### ISSUE TITLE
Stavekontroll blir bygd utan problem lokalt, feilar i CI/CD

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sma#101]
I dei siste CI-byggingane så stoppar stavekontrollbygginga i `make check`, `accept-all-lemmas.sh `, jf https://github.com/giellalt/lang-sma/runs/29243981837

Den same testen går gjennom på mi eiga maskin:

```
Making check in test
Making check in fstbased
Making check in desktop
Making check in hfst
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: test-zhfst-basic-sugg-speed.sh
PASS: accept-all-lemmas.sh
============================================================================
Testsuite summary for Giella sma 0.2.0
============================================================================
# TOTAL: 2
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

Dermed kan det sjå ut som ein skilnad på Linux vs mac. @flammie kan du sjå på dette?

**Comment by snomos** [comment]
@flammie kva er stoda? Problemet er enno der.

**Comment by flammie** [comment]
det gir PASS på min linux også, jeg ska pröve å debugge task cluster på noen mote

**Comment by flammie** [comment]
```
FAIL: accept-all-lemmas.sh
==========================
fail(Bed to ospellfailed
```
seems like a problem with hfst-ospell altogether...  I guess the command line tool that is needed is not installed at all
