### ISSUE TITLE
Rangering av korrekt ordvalg

### ISSUE THREAD

**Issue by Samama74** [giellalt/lang-sma#13]
<img width="491" alt="Skjermbilde 2022-10-31 kl  12 20 39" src="https://user-images.githubusercontent.com/57760818/198997321-b7fe9721-9722-48eb-b2c3-c43387a71796.png">

Foreslår bedre rangering av korrekt ordvalg - maehtieh bör komme överst. 

/Marja

**Comment by snomos** [comment]
Takk for meldinga, skal sjå om vi får til det 🙂

**Comment by snomos** [comment]
No får eg forslaget på tredje plass:

```shell
echo maehttie | divvunspell suggest -a tools/spellcheckers/sma.zhfst
Reading from stdin...
Input: maehttie		[INCORRECT]
meehtie		36.49508
maehtebe		37.823006
maehtieh		38.285595
maehtede		40.984253
mehtie		40.984253
miehtjie		41.495083
maehtsieh		44.49508
daehtie		49.038345
aehtjie		49.26149
meehtieh		53.49508
```

Høgare tør eg ikkje løfta det, i frykt for å øydeleggja andre forslag.
