### ISSUE TITLE
lang-sma does not compile

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-sma#15]
Error message: `No rule to make target `analyser-oahpa-gt-norm-dial_L.hfstol'`
Configure line `./configure --enable-all-tools`

Up-to-date shared-mul, shared-smi, giella-core

**Comment by flammie** [comment]
it worked for me up to:
```
make[3]: Verzeichnis „/home/flammie/github/giellalt/lang-sma/tools/tokenisers/filters“ wird betreten
make[3]: *** Keine Regel vorhanden, um das Ziel „make-disamb-CG-tags.hfst“, benötigt von „all-am“, zu erstellen.  Schluss.
```

**Comment by albbas** [comment]
Sjur's quickfix, comment out `AC_SUBST([DIALECTS], ["L SH SW NOR"])` from configure.ac

**Comment by albbas** [comment]
It seems the temporary solution is good enough :)
