### ISSUE TITLE
src/filters/remove-norm-comp-tags.hfst missing?

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-sma#18]
`./configure --enable-all-tools --without-forrest --with-hfst --enable-tokenisers --without-xfst --enable-reversed-intersect --enable-spellers --enable-hfst-mobile-speller --enable-alignment --disable-minimised-spellers --enable-syntax --enable-analysers --enable-generators --enable-apertium --enable-grammarchecker --enable-dicts --enable-oahpa --enable-morpher --disable-hfst-desktop-spellers`

yields:
```
make[4]: Entering directory '/build/giella-sma-0.2.0+g12576~4c0df9ba-1~sid1/tools/mt'
Makefile:1202: warning: overriding recipe for target 'clean-local'
Makefile:1184: warning: ignoring old recipe for target 'clean-local'
/usr/bin/mkdir -p `dirname .generated/.stamp`
make[4]: *** No rule to make target '../../src/filters/remove-norm-comp-tags.hfst', needed by 'analyser-mt-gt-desc.hfst'.  Stop.
```

**Comment by flammie** [comment]
just affected by the recent move, thanks fro the report there's gonna be quite a few of these in language specific rules still. (all src/filters and src/orthography should have fst/ now)
