### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by flammie** [giellalt/lang-sma#2]
to fix:
https://github.com/giellalt/lang-sma/runs/1044614527#step:7:1984

**Comment by snomos** [comment]
The run log has expired and are not available anymore. What was the issue? Or could it be closed?

**Comment by flammie** [comment]
Yeah I think this was the segfault in foma with some regexes, it's worked-around in current hfst version of foma so it can be closed I guess everyone should have new enough hfst by now

**Comment by snomos** [comment]
Cool. I close.
