### ISSUE TITLE
./configure gives error

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-sma#4]
config.status: error: cannot find input file: `tools/tokenisers/Makefile.in'

**Comment by flammie** [comment]
`autogen.sh` (or `autoreconf`) is needed to generate `Makefile.am` from `Makefile.in`? Also the file list probably comes from giella-core so that may need update.

**Comment by albbas** [comment]
I get the same error, giella-core is updated, when I run the following commands:
```
 git reset --hard
 git clean -fx
 git pull --rebase
./autogen.sh && ./configure
…
config.status: creating tools/mt/cgbased/Makefile
config.status: error: cannot find input file: `tools/tokenisers/Makefile.in'
…
```

**Comment by albbas** [comment]
Sorry, was in the master branch. When switching to develop everything works …
