### ISSUE TITLE
IDENTITETE får feil forslag

### ISSUE THREAD

**Issue by Samama74** [giellalt/lang-sma#5]
Forslagene som gis, blir foreslått med bindestrek. Det gjelder generelt sett når man skriver overskrifter med blokkbokstaver. 
 Versjon av stavekontroll: sma, desktop, version 4.2.2, 07.09.2020-0726

<img width="404" alt="Skjermbilde 2020-11-17 kl  13 48 39" src="https://user-images.githubusercontent.com/57760818/99392367-e29fbb80-28db-11eb-91ec-92f96b39101b.png">

**Comment by snomos** [comment]
Med divvunspell (som er det som blir bruk i systemstavekontrollen på mac og i mobiltastaturet) får eg dette:

```sh
echo IDENTITETE | divvunspell suggest -a tools/spellcheckers/sma.zhfst 
Reading from stdin...
Input: IDENTITETE		[INCORRECT]
Identiteete		82.49508
Identiteetem		116.20703
Identiteeten		117.49508
Identiteeth		117.49508
Identiteeti		117.49508
```

**Comment by albbas** [comment]
Resultatet ovenfor er fra LibreOffice, med fersk sma.zhfst i ~/Library/Spelling/voikko/3/sma.zhfst

**Comment by snomos** [comment]
Jepp. Og no har eg sagt til @Samama74 at ho ikkje skal testa med LibreOffice.

Alle dei andre stavekontrollane våre bruker `divvunspell`, og vi vil oppdatera LO-stavekontrollen til å nytta den same (truleg ikkje før på nyåret). Dvs at for å få relevante og gode feilmeldingar, som gjeld både mobilstavekontrollane, og stavekontrollane for Windows og mac (minus altså LO), så bør ho testa i SEE, TextEdit, Mail, eller eit anna program som nyttar systemstavekontrollen på macen.

**Comment by snomos** [comment]
Som det kjem fram av dømet mitt over så finst det ein annan feil, som eg kjem til å rapportera til folka i Gøteborg - nemleg at forslag for ord som er skrivne med berre store bokstavar bør òg vera med berre store bokstavar :)

**Comment by snomos** [comment]
Eg har meldt feilen med manglande store bokstavar vidare, og avsluttar denne lusmeldinga.
